services:
  postgres:
    image: postgres:16-alpine
    container_name: hungrybuy-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pghungrybuy:/var/lib/postgresql/data/
    networks:
      - app-network

  server:
    build:
      context: ./server
    container_name: hungrybuy-server-dev
    command: npm run dev
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  client:
    build:
      context: ./client
    container_name: hungrybuy-client-dev
    command: npm run dev
    env_file:
      - ./client/.env
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

  admin:
    build:
      context: ./admin
    container_name: hungrybuy-admin-dev
    command: npm run dev
    env_file:
      - ./admin/.env
    depends_on:
      - server
    ports:
      - "8000:3000"
    volumes:
      - ./admin:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

volumes:
  pghungrybuy:
    name: hungrybuy

networks:
  app-network:
    name: hungrybuy-net
    driver: bridge
