services:
  postgres:
    image: postgres:16-alpine
    container_name: hungrybuy-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pghungrybuy:/var/lib/postgresql/data/

  server:
    build:
      context: ./server
    container_name: hungrybuy-server
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  client:
    build:
      context: ./client
    container_name: hungrybuy-client
    env_file:
      - ./client/.env
    depends_on:
      - server
    ports:
      - "3000:3000"

  admin:
    build:
      context: ./admin
    container_name: hungrybuy-admin
    env_file:
      - ./admin/.env
    depends_on:
      - server
    ports:
      - "8000:8000"

volumes:
  pghungrybuy:
    name: hungrybuy
