services:
  postgres:
    image: postgres:16-alpine
    container_name: hungrybuy-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pghungrybuy:/var/lib/postgresql/data/4
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: hungrybuy-redis
    command: >
      sh -c "
      --appendonly yes
      --maxmemory ${REDIS_MAX_MEMORY}
      --maxmemory-policy ${REDIS_MAX_MEMORY_POLICY}
      --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redisdata:/data
    networks:
      - app-network

  server:
    build:
      context: ./server
    container_name: hungrybuy-server
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    networks:
      - app-network

  client:
    build:
      context: ./client
    container_name: hungrybuy-client
    env_file:
      - ./client/.env
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

  admin:
    build:
      context: ./admin
    container_name: hungrybuy-admin
    env_file:
      - ./admin/.env
    depends_on:
      - server
    ports:
      - "8000:3000"
    networks:
      - app-network

volumes:
  pghungrybuy:
    name: hungrybuy
  redisdata:
    name: hungryredis

networks:
  app-network:
    name: hungrybuy-net
    driver: bridge
    internal: true
