services:
  postgres:
    image: postgres:16-alpine
    container_name: hungrybuy-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pghungrybuy:/var/lib/postgresql/data/
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: hungrybuy-redis
    command: >
      sh -c "
      --appendonly yes
      --maxmemory ${REDIS_MAX_MEMORY}
      --maxmemory-policy ${REDIS_MAX_MEMORY_POLICY}
      --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: hungrybuy-server-dev
    command: npm run dev
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: hungrybuy-client-dev
    command: npm run dev
    env_file:
      - ./client/.env
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    container_name: hungrybuy-admin-dev
    command: npm run dev
    env_file:
      - ./admin/.env
    depends_on:
      - server
    ports:
      - "8000:3000"
    volumes:
      - ./admin:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

volumes:
  pghungrybuy:
    name: hungrybuy
  redisdata:
    name: hungryredis

networks:
  app-network:
    name: hungrybuy-net
    driver: bridge
